name: Api

on:
  push:
    branches:
      - main
  pull_request:
    branches:
          types: [opened, synchronize, reopened, ready_for_review]
  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: SetUp Node.js
          uses: actions/setup-node@v1
          with:
            node-version: "16.13.2"
        
        - run: |
            yarn
            yarn --cwd api test

